---
- name: Install Jenkins on Ubuntu
  hosts: jenkins-master
  become: yes
  tasks:
    - name: Add Jenkins APT key
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        state: present

    - name: Add Jenkins APT repository
      apt_repository:
        repo: deb http://pkg.jenkins.io/debian-stable binary/
        state: present

    - name: install java
      apt:
        name: openjdk-11-jre
        state: present   

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Start Jenkins service
      service:
        name: jenkins
        state: started

    - name: enable jenkins to start at boot time
      service:
        name: jenkins
        enable: yes